package:
  name: pypsf
  version: "1.0"

source:
  git_url: git@github.com:pkerichang/libpsf.git

build:
  number: 0

requirements:
  build:
    - python
    - cython
    - numpy
    - gcc
    - libpsf
  run:
    - python
    - numpy
    - libgcc
    - libpsf

about:
  home: https://github.com/pkerichang/libpsf
  license: LGPL
