package:
  name: libpsf
  version: "1.0"

source:
  git_url: https://github.com/blorgon9000/libpsf.git

build:
  number: 0

requirements:
  build:
    - gcc
  run:
    - libgcc

about:
  home: https://github.com/blorgon9000/libpsf
  license: LGPL
